version: "3"
services:
  db:
    image: mysql:8
    container_name: admin-refine_mysql
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_USER: datproto
      MYSQL_PASSWORD: datproto_mysql
      MYSQL_DATABASE: datproto_db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin-refine_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  backend:
    container_name: admin-refine_backend
    build: 
      dockerfile: Dockerfile
      context: ./api
      target: development
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000
      - 9229:9229
    restart: always
    command: yarn start:dev
    links:
      - db:db
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
  