version: "3"
services:
  db:
    image: mysql:8
    container_name: invoice-app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_USER: datproto
      MYSQL_PASSWORD: datproto_mysql
      MYSQL_DATABASE: datproto_db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: invoice-app_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  admin:
    container_name: invoice-app_admin
    image: node:16-alpine
    working_dir: /usr/src/admin
    user: 1000:1000
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3001:3000
      - 35729:35729
    restart: always
    command: yarn dev
    links:
      - db:db
    volumes:
      - ./admin:/usr/src/admin
      - ./admin/node_modules:/usr/src/admin/node_modules
  backend:
    container_name: invoice-app_backend
    image: node:16-alpine
    working_dir: /usr/src/api
    user: 1000:1000
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000
      - 9229:9229
    restart: always
    command: yarn start:dev
    links:
      - db:db
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
  frontend:
    container_name: invoice-app_frontend
    image: node:16-alpine
    working_dir: /usr/src/app
    user: 1000:1000
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    restart: always
    command: yarn dev
    links:
      - db:db
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
  storybook:
    container_name: invoice-app_storybook
    image: node:16-alpine
    working_dir: /usr/src/storybook
    user: 1000:1000
    depends_on:
      - db
    ports:
      - 6006:6006
    restart: always
    command: yarn storybook
    links:
      - db:db
    volumes:
      - ./app:/usr/src/storybook
      - ./app/node_modules:/usr/src/storybook/node_modules
  