import type { NextPage } from 'next'
import Head from 'next/head'

import Navbar from '@/components/molecules/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col w-full xl:flex-row bg-lightGray dark:bg-navi-300">
        <Navbar />
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
